import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.swifttranslator.com/');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('naee, mata 7');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('naee, mata 7AM ');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('naee, mata 7AM walata zoom meeting ekata join venna baeri i');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('naee, mata 7AM valata zoom meeting ekata join venna baeri i');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).fill('naee, mata 7AM valata zoom meeting ekata join venna baeri unaa, ee nisaa mama ee gaena hariyatama dhanne naee. mata ee meeting eka gaena kiyala dhenna puluvandha?');
  await page.getByRole('textbox', { name: 'Input Your Singlish Text Here.' }).click();
  await page.getByText('නෑ, මට 7AM වලට zoom meeting').click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Copy' }).first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Copy' }).nth(1).click();
});